name: Build and Release apk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          # distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.3'
      - run: flutter pub get
  #     - run: flutter test
      - run: flutter build apk --release --target-platform android-arm64
  
